export const MAX_PLAINTEXT_FILE_BYTES = 8 * 1024 * 1024;
export const MAX_FILE_METADATA_BYTES = 4 * 1024;
export const FILE_ENCRYPTION_OVERHEAD_BYTES = 4 + 16;
export const MAX_CIPHERTEXT_FILE_BYTES =
  MAX_PLAINTEXT_FILE_BYTES +
  MAX_FILE_METADATA_BYTES +
  FILE_ENCRYPTION_OVERHEAD_BYTES;
